apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: sschouhan-tk-tls
spec:
  secretName: sschouhan-tk
  duration: 24h
  renewBefore: 12h
  issuerRef:
    name: letsencrpt-prod
    kind: ClusterIssuer
  commonName: sschouhan.tk
  dnsNames:
    - sschouhan.tk
    - www.sschouhan.tk
  