apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: sschouhan-tk-tls
spec:
  secretName: sschouhan-tk
  issuerRef:
    name: letsencrpt-prod
    kind: ClusterIssuer
  commonName: sschouhan.tk
  dnsNames:
    - sschouhan.tk
    - www.sschouhan.tk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - sschouhan.tk
          - www.sschouhan.tk