apiVersion: cert-manager.io/v1
kind: CertificateRequest
metadata:
  name: sschouhan-tk-tls
spec:
  secretName: sschouhan-tk
  issuerRef:
    name: letsencrpt-prod
    kind: Issuer
  commonName: sschouhan.tk
  dnsNames:
    - sschouhan.tk
    - www.sschouhan.tk
  