apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'coolshaddy81@gmail.com'
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
    